version: '3.8'
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: node-backend
    ports:
      - '80:80'
      - '9229:9229'
    volumes:
      - ./:/opt

