version: '3.8'
services:
  db:
    image: mysql:8-oracle
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
